//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebServiceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebServiceMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebServiceMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sudah dibatalkan.
        /// </summary>
        internal static string CancelAlert {
            get {
                return ResourceManager.GetString("CancelAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sudah dikonfirmasi.
        /// </summary>
        internal static string ConfirmAlert {
            get {
                return ResourceManager.GetString("ConfirmAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanggal wajib diisi.
        /// </summary>
        internal static string DateNullAlert {
            get {
                return ResourceManager.GetString("DateNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sudah selesai.
        /// </summary>
        internal static string FinishAlert {
            get {
                return ResourceManager.GetString("FinishAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sudah berjalan.
        /// </summary>
        internal static string GoAlert {
            get {
                return ResourceManager.GetString("GoAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order belum dimulai.
        /// </summary>
        internal static string NewAlert {
            get {
                return ResourceManager.GetString("NewAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak memiliki akses.
        /// </summary>
        internal static string NotAccess {
            get {
                return ResourceManager.GetString("NotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kode Booking tidak ditemukan.
        /// </summary>
        internal static string OrderNotFoundAlert {
            get {
                return ResourceManager.GetString("OrderNotFoundAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order wajib diisi.
        /// </summary>
        internal static string OrderNullAlert {
            get {
                return ResourceManager.GetString("OrderNullAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak memiliki akses.
        /// </summary>
        internal static string UsernameAlert {
            get {
                return ResourceManager.GetString("UsernameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Anda tidak ditemukan.
        /// </summary>
        internal static string UsernameNullAlert {
            get {
                return ResourceManager.GetString("UsernameNullAlert", resourceCulture);
            }
        }
    }
}
