//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actions
    {
        public Actions()
        {
            this.Modules = new HashSet<Modules>();
            this.ModulesInRoles = new HashSet<ModulesInRoles>();
        }
    
        public System.Guid Id { get; set; }
        public string ActionName { get; set; }
    
        public virtual ICollection<Modules> Modules { get; set; }
        public virtual ICollection<ModulesInRoles> ModulesInRoles { get; set; }
    }
}
