//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_rent
    {
        public api_rent()
        {
            this.log_api_rent = new HashSet<log_api_rent>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid id_rent { get; set; }
        public string partner { get; set; }
        public string status { get; set; }
        public string cancellation_status { get; set; }
    
        public virtual rent rent { get; set; }
        public virtual ICollection<log_api_rent> log_api_rent { get; set; }
    }
}
