//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Memberships = new HashSet<Membership>();
            this.Roles = new HashSet<roles>();
            this.Users = new HashSet<users>();
        }
    
        public string ApplicationName { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Membership> Memberships { get; set; }
        public virtual ICollection<roles> Roles { get; set; }
        public virtual ICollection<users> Users { get; set; }
    }
}
