//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_expense
    {
        public System.Guid id { get; set; }
        public System.DateTime expense_date { get; set; }
        public System.Guid id_car { get; set; }
        public string expense_type { get; set; }
        public string other { get; set; }
        public Nullable<int> distance { get; set; }
        public int expense_value { get; set; }
        public string attachment { get; set; }
        public string notes { get; set; }
        public string created_by { get; set; }
        public System.DateTimeOffset created_time { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTimeOffset> updated_time { get; set; }
    
        public virtual car car { get; set; }
    }
}
