//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_package
    {
        public car_package()
        {
            this.rent_package = new HashSet<rent_package>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid id_car_model { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public string created_by { get; set; }
        public System.DateTimeOffset created_time { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTimeOffset> updated_time { get; set; }
        public bool is_active { get; set; }
        public System.Guid id_owner { get; set; }
    
        public virtual car_model car_model { get; set; }
        public virtual owner owner { get; set; }
        public virtual ICollection<rent_package> rent_package { get; set; }
    }
}
