//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_model
    {
        public car_model()
        {
            this.cars = new HashSet<car>();
            this.car_package = new HashSet<car_package>();
            this.rents = new HashSet<rent>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public System.Guid id_car_brand { get; set; }
        public short capacity { get; set; }
    
        public virtual ICollection<car> cars { get; set; }
        public virtual car_brand car_brand { get; set; }
        public virtual ICollection<car_package> car_package { get; set; }
        public virtual ICollection<rent> rents { get; set; }
    }
}
