//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.rents = new HashSet<rent>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string customer_type { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public string notes { get; set; }
        public System.Guid id_owner { get; set; }
        public string title { get; set; }
        public string company { get; set; }
        public string photo { get; set; }
    
        public virtual owner owner { get; set; }
        public virtual ICollection<rent> rents { get; set; }
    }
}
