//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public expense()
        {
            this.expense_item = new HashSet<expense_item>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid id_rent { get; set; }
        public System.DateTime date { get; set; }
        public string created_by { get; set; }
        public System.DateTimeOffset created_time { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTimeOffset> updated_time { get; set; }
    
        public virtual ICollection<expense_item> expense_item { get; set; }
        public virtual rent rent { get; set; }
    }
}
