//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.invoice_item = new HashSet<invoice_item>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid id_rent { get; set; }
        public int price { get; set; }
        public string code { get; set; }
        public System.DateTime invoice_date { get; set; }
        public string status { get; set; }
        public string cancel_notes { get; set; }
        public string created_by { get; set; }
        public System.DateTimeOffset created_time { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTimeOffset> updated_time { get; set; }
        public bool ppn { get; set; }
        public int total { get; set; }
    
        public virtual ICollection<invoice_item> invoice_item { get; set; }
        public virtual rent rent { get; set; }
    }
}
