//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_api_rent
    {
        public System.Guid id { get; set; }
        public System.Guid id_api_rent { get; set; }
        public string status { get; set; }
        public System.DateTimeOffset created_time { get; set; }
    
        public virtual api_rent api_rent { get; set; }
    }
}
