//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<api_rent> api_rent { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<car_brand> car_brand { get; set; }
        public virtual DbSet<car_expense> car_expense { get; set; }
        public virtual DbSet<car_model> car_model { get; set; }
        public virtual DbSet<car_package> car_package { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<d_notification> d_notification { get; set; }
        public virtual DbSet<driver> drivers { get; set; }
        public virtual DbSet<expense> expenses { get; set; }
        public virtual DbSet<expense_item> expense_item { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<invoice_item> invoice_item { get; set; }
        public virtual DbSet<log_api_rent> log_api_rent { get; set; }
        public virtual DbSet<log_ws> log_ws { get; set; }
        public virtual DbSet<owner> owners { get; set; }
        public virtual DbSet<owner_user> owner_user { get; set; }
        public virtual DbSet<rent> rents { get; set; }
        public virtual DbSet<rent_code> rent_code { get; set; }
        public virtual DbSet<rent_package> rent_package { get; set; }
        public virtual DbSet<rent_position> rent_position { get; set; }
    }
}
