//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public Modules()
        {
            this.ModulesInRoles = new HashSet<ModulesInRoles>();
            this.Actions = new HashSet<Actions>();
        }
    
        public System.Guid Id { get; set; }
        public string ModuleName { get; set; }
        public string ParentModule { get; set; }
    
        public virtual ICollection<ModulesInRoles> ModulesInRoles { get; set; }
        public virtual ICollection<Actions> Actions { get; set; }
    }
}
