//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulesInRoles
    {
        public ModulesInRoles()
        {
            this.Actions = new HashSet<Actions>();
        }
    
        public System.Guid ModuleId { get; set; }
        public int RoleId { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<Actions> Actions { get; set; }
    }
}
