//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner_user
    {
        public System.Guid id_owner { get; set; }
        public string username { get; set; }
        public System.Guid id { get; set; }
    
        public virtual owner owner { get; set; }
    }
}
