//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent_position
    {
        public System.Guid id { get; set; }
        public System.Guid id_rent { get; set; }
        public string created_by { get; set; }
        public System.DateTimeOffset created_time { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
    
        public virtual rent rent { get; set; }
    }
}
