//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public roles()
        {
            this.ModulesInRoles = new HashSet<ModulesInRoles>();
            this.users = new HashSet<users>();
        }
    
        public int role_id { get; set; }
        public string role_name { get; set; }
        public string application_name { get; set; }
        public string role_description { get; set; }
    
        public virtual ICollection<ModulesInRoles> ModulesInRoles { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
