//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_login_activity
    {
        public int activity_id { get; set; }
        public System.DateTimeOffset when { get; set; }
        public string from { get; set; }
        public bool success { get; set; }
        public int user_id { get; set; }
    }
}
