//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.roles = new HashSet<roles>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string application_name { get; set; }
        public Nullable<System.DateTimeOffset> last_activity { get; set; }
        public System.DateTimeOffset created { get; set; }
        public string email { get; set; }
        public string salt { get; set; }
        public byte[] password { get; set; }
        public bool approved { get; set; }
        public Nullable<System.DateTimeOffset> last_lockout { get; set; }
        public Nullable<System.DateTimeOffset> last_login { get; set; }
        public System.DateTimeOffset last_password_changed { get; set; }
        public string password_question { get; set; }
        public byte[] password_answer { get; set; }
        public string answer_salt { get; set; }
        public string comment { get; set; }
    
        public virtual ICollection<roles> roles { get; set; }
    }
}
